apiVersion: v1
kind: Pod
metadata:
  name: mypodlifecycle
  labels:
    app: mybluepod
spec:
  containers:
    - name: demo
      image: nginx:1.29
      ports:
        - containerPort: 80
  resources:
    requests:
      cpu: 250m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
